version: "3.1"

services:
  backend:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 4000:4000
    volumes:
      - .:/app
    environment:
      - MONGO_URI=mongodb://admin:password@mongo:27017/test?authSource=admin
      - MONGO_DATABASE=demo
    depends_on:
      - mongo

  mongo:
    image: mongo:4.4.3
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017
    volumes:
      - ./db:/data/db
      - ./configdb:/data/configdb
# mongodb://admin:password@localhost:27017/test
