version: "3.1"

services:
  backend:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
    volumes:
      - .:/app
    environment:
      - MONGO_URI=mongodb://admin:password@mongo:27017/test?authSource=admin
      - MONGO_DATABASE=demo
      - X_API_KEY=aijdfoiajpdfioj
      - JWT_SECRET=eipjdfpaijdpfa
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo:4.4.3
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017
    volumes:
      - ./db:/data/db
      - ./configdb:/data/configdb
  # mongodb://admin:password@localhost:27017/test

  redis:
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - ./redis/conf:/usr/local/etc/redis

  # redis-gui:
  #   image: redislabs/redisinsight:latest
  #   ports:
  #     - 8001:8001
  #   links:
  #     - redis
